services:
  payload:
    image: node:22.17.0-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && pnpm install --frozen-lockfile && pnpm payload migrate && pnpm dev"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://payload:payload@postgres:5432/villa_san_antonio

  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: villa_san_antonio
      POSTGRES_PASSWORD: payload
      POSTGRES_USER: payload
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U payload -d villa_san_antonio']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
