/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'discover-posts': DiscoverPost;
    'discover-categories': DiscoverCategory;
    'drives-distances': DrivesDistance;
    media: Media;
    'gallery-images': GalleryImage;
    'gallery-categories': GalleryCategory;
    reviews: Review;
    'faq-items': FaqItem;
    'faq-categories': FaqCategory;
    'booking-inquiries': BookingInquiry;
    'contact-messages': ContactMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'discover-posts': DiscoverPostsSelect<false> | DiscoverPostsSelect<true>;
    'discover-categories': DiscoverCategoriesSelect<false> | DiscoverCategoriesSelect<true>;
    'drives-distances': DrivesDistancesSelect<false> | DrivesDistancesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    'gallery-categories': GalleryCategoriesSelect<false> | GalleryCategoriesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'faq-categories': FaqCategoriesSelect<false> | FaqCategoriesSelect<true>;
    'booking-inquiries': BookingInquiriesSelect<false> | BookingInquiriesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?:
    | (
        | {
            slides: {
              image: number | Media;
              kicker?: string | null;
              title: string;
              accent?: string | null;
              subtext?: string | null;
              id?: string | null;
            }[];
            transitionDuration?: number | null;
            interval?: number | null;
            primaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            coordsText?: string | null;
            scrollLabel?: string | null;
            instagramUrl?: string | null;
            facebookUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-slider';
          }
        | {
            title: string;
            accent?: string | null;
            lead?: string | null;
            /**
             * Overrides the default breadcrumb trail label
             */
            breadcrumbLabel?: string | null;
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-sub';
          }
        | {
            kicker?: string | null;
            title: string;
            accent?: string | null;
            badge?: string | null;
            showMap?: boolean | null;
            mapEmbedUrl?: string | null;
            mapDirectUrl?: string | null;
            mapAddress?: string | null;
            lead: string;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            highlights?:
              | {
                  icon?: ('users' | 'pool' | 'flame' | 'paw' | 'bed' | 'sun' | 'sparkles') | null;
                  label: string;
                  detail: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'storyHighlights';
          }
        | {
            kicker?: string | null;
            title: string;
            accent?: string | null;
            bgStyle?: ('surface' | 'paper') | null;
            spaces?:
              | {
                  /**
                   * e.g. Kitchen & Dining, Master Bedroom, BBQ House
                   */
                  name: string;
                  /**
                   * e.g. interior, bedrooms, bathrooms, outdoors
                   */
                  category?: string | null;
                  subtitle?: string | null;
                  images?:
                    | {
                        image: number | Media;
                        id?: string | null;
                      }[]
                    | null;
                  features?:
                    | {
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacesShowcase';
          }
        | {
            kicker?: string | null;
            headline: string;
            accent?: string | null;
            body: string;
            delicacies?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            imageMain?: (number | null) | Media;
            imageTop?: (number | null) | Media;
            imageBottom?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'welcomePackage';
          }
        | {
            kicker?: string | null;
            title: string;
            accent?: string | null;
            items?:
              | {
                  /**
                   * e.g. 14 km, 20 min, 1.5 km
                   */
                  value: string;
                  /**
                   * e.g. Nearest beach, Šibenik old town, Split airport
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'distances';
          }
        | {
            title: string;
            accent?: string | null;
            body?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaLink?: string | null;
            whatsappLabel?: string | null;
            whatsappNumber?: string | null;
            hostName?: string | null;
            hostRole?: string | null;
            hostInitials?: string | null;
            /**
             * Profile picture of the host (circular). If left empty, initials will be displayed.
             */
            hostAvatar?: (number | null) | Media;
            hostPhone?: string | null;
            hostEmail?: string | null;
            guarantees?:
              | {
                  icon?: ('shield' | 'receipt' | 'sparkles' | 'clock' | 'paw' | 'pool' | 'users' | 'star') | null;
                  title: string;
                  desc: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bookingBand';
          }
        | {
            kicker?: string | null;
            title: string;
            accent?: string | null;
            titleEnd?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            primaryImage?: (number | null) | Media;
            secondaryImage?: (number | null) | Media;
            stats?:
              | {
                  label: string;
                  value: number;
                  suffix?: string | null;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'perspective';
          }
        | {
            quote: string;
            author?: string | null;
            role?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            kicker?: string | null;
            title: string;
            accent?: string | null;
            items?:
              | {
                  name: string;
                  tag?: string | null;
                  time?: string | null;
                  desc?: string | null;
                  image?: (number | null) | Media;
                  link?: string | null;
                  icon?: ('sun' | 'flame' | 'moon' | 'sparkles' | 'clock') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'places';
          }
        | {
            kicker?: string | null;
            title: string;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regionalDrivesText';
          }
        | {
            kicker?: string | null;
            title?: string | null;
            accent?: string | null;
            /**
             * Duration in seconds for one full loop cycle. Lower number = faster movement, higher number = slower movement (e.g. 45 for fast, 65 for default, 90 for slow).
             */
            speed?: number | null;
            images?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'galleryStrip';
          }
        | {
            kicker?: string | null;
            title?: string | null;
            accent?: string | null;
            intro?: string | null;
            limit?: number | null;
            selectedReviews?: (number | Review)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviews';
          }
        | {
            kicker?: string | null;
            title?: string | null;
            accent?: string | null;
            subtext?: string | null;
            items?: (number | FaqItem)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqShort';
          }
        | {
            leftKicker?: string | null;
            leftTitle?: string | null;
            leftAccent?: string | null;
            leftLead?: string | null;
            quickFacts?:
              | {
                  icon?: ('clock' | 'shield' | 'pool' | 'paw' | 'wifi' | 'flame' | 'users') | null;
                  title: string;
                  value: string;
                  subtitle?: string | null;
                  id?: string | null;
                }[]
              | null;
            rightKicker?: string | null;
            rightTitle?: string | null;
            rightAccent?: string | null;
            rightLead?: string | null;
            enableSearch?: boolean | null;
            enableCategoryTabs?: boolean | null;
            /**
             * Select specific FAQ items to display in order, or leave empty to automatically display all FAQ items from the collection.
             */
            items?: (number | FaqItem)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqSection';
          }
        | {
            kicker?: string | null;
            title?: string | null;
            accent?: string | null;
            lead?: string | null;
            email?: string | null;
            phone?: string | null;
            whatsappNumber?: string | null;
            whatsappLabel?: string | null;
            locationAddress?: string | null;
            googleMapsUrl?: string | null;
            showFaqCard?: boolean | null;
            faqCardTitle?: string | null;
            faqCardText?: string | null;
            faqCardLinkLabel?: string | null;
            faqCardLinkUrl?: string | null;
            enableMap?: boolean | null;
            mapLatitude?: number | null;
            mapLongitude?: number | null;
            mapZoom?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSection';
          }
        | {
            stepsTitle?: string | null;
            steps?:
              | {
                  num?: string | null;
                  title: string;
                  desc: string;
                  id?: string | null;
                }[]
              | null;
            privilegesTitle?: string | null;
            privileges?:
              | {
                  icon?: ('shield' | 'sparkles' | 'clock' | 'heart' | 'check') | null;
                  title: string;
                  desc: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Upload a personal portrait photo of Josip / Hosts. If empty, initials will be shown.
             */
            hostImage?: (number | null) | Media;
            hostName?: string | null;
            hostSubtitle?: string | null;
            badgeText?: string | null;
            whatsappLabel?: string | null;
            whatsappNumber?: string | null;
            phone?: string | null;
            email?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bookingSection';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL slug for this page (e.g. "home", "about-villa", "gallery")
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  country?: string | null;
  /**
   * Guest rating from 1 to 5
   */
  stars?: number | null;
  text: string;
  /**
   * e.g. adriaticluxuryvillas.com
   */
  source?: string | null;
  /**
   * Link to the original review
   */
  sourceUrl?: string | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: string;
  category?: (number | null) | FaqCategory;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categories".
 */
export interface FaqCategory {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (auto-generated from Name, click Unlock to edit)
   */
  slug: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create one post per local experience. Drag rows by the handle in the list to change their frontend order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discover-posts".
 */
export interface DiscoverPost {
  id: number;
  _order?: string | null;
  title: string;
  categoryRef: number | DiscoverCategory;
  tag?: string | null;
  badge?: string | null;
  externalLink?: string | null;
  /**
   * Direct Google Maps destination URL
   */
  mapsUrl?: string | null;
  desc: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categories shown as filters on the Discover page. Drag rows to change their frontend order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discover-categories".
 */
export interface DiscoverCategory {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Used as the frontend filter identifier.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create one post per destination. Drag rows by the handle in the list to change their frontend order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drives-distances".
 */
export interface DrivesDistance {
  id: number;
  _order?: string | null;
  name: string;
  category?: string | null;
  distance: string;
  driveTime: string;
  mapsUrl?: string | null;
  desc?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  image: number | Media;
  /**
   * Overrides the media alt text if filled in
   */
  alt?: string | null;
  category?: (number | null) | GalleryCategory;
  /**
   * Featured images are prioritized in hero and highlights
   */
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories".
 */
export interface GalleryCategory {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (auto-generated from Name, click Unlock to edit)
   */
  slug: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-inquiries".
 */
export interface BookingInquiry {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  country?: string | null;
  checkIn: string;
  checkOut: string;
  adults: number;
  kids?: number | null;
  pets: 'no' | 'yes';
  notes?: string | null;
  status?: ('new' | 'contacted' | 'booked' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  subject: string;
  message: string;
  /**
   * The sender agreed to personal data processing
   */
  consent: boolean;
  status?: ('new' | 'handled' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'discover-posts';
        value: number | DiscoverPost;
      } | null)
    | ({
        relationTo: 'discover-categories';
        value: number | DiscoverCategory;
      } | null)
    | ({
        relationTo: 'drives-distances';
        value: number | DrivesDistance;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'gallery-categories';
        value: number | GalleryCategory;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'faq-categories';
        value: number | FaqCategory;
      } | null)
    | ({
        relationTo: 'booking-inquiries';
        value: number | BookingInquiry;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        'hero-slider'?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    kicker?: T;
                    title?: T;
                    accent?: T;
                    subtext?: T;
                    id?: T;
                  };
              transitionDuration?: T;
              interval?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              coordsText?: T;
              scrollLabel?: T;
              instagramUrl?: T;
              facebookUrl?: T;
              id?: T;
              blockName?: T;
            };
        'hero-sub'?:
          | T
          | {
              title?: T;
              accent?: T;
              lead?: T;
              breadcrumbLabel?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        storyHighlights?:
          | T
          | {
              kicker?: T;
              title?: T;
              accent?: T;
              badge?: T;
              showMap?: T;
              mapEmbedUrl?: T;
              mapDirectUrl?: T;
              mapAddress?: T;
              lead?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              highlights?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        spacesShowcase?:
          | T
          | {
              kicker?: T;
              title?: T;
              accent?: T;
              bgStyle?: T;
              spaces?:
                | T
                | {
                    name?: T;
                    category?: T;
                    subtitle?: T;
                    images?:
                      | T
                      | {
                          image?: T;
                          id?: T;
                        };
                    features?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        welcomePackage?:
          | T
          | {
              kicker?: T;
              headline?: T;
              accent?: T;
              body?: T;
              delicacies?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              imageMain?: T;
              imageTop?: T;
              imageBottom?: T;
              id?: T;
              blockName?: T;
            };
        distances?:
          | T
          | {
              kicker?: T;
              title?: T;
              accent?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bookingBand?:
          | T
          | {
              title?: T;
              accent?: T;
              body?: T;
              primaryCtaLabel?: T;
              primaryCtaLink?: T;
              whatsappLabel?: T;
              whatsappNumber?: T;
              hostName?: T;
              hostRole?: T;
              hostInitials?: T;
              hostAvatar?: T;
              hostPhone?: T;
              hostEmail?: T;
              guarantees?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        perspective?:
          | T
          | {
              kicker?: T;
              title?: T;
              accent?: T;
              titleEnd?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              primaryImage?: T;
              secondaryImage?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    suffix?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              author?: T;
              role?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        places?:
          | T
          | {
              kicker?: T;
              title?: T;
              accent?: T;
              items?:
                | T
                | {
                    name?: T;
                    tag?: T;
                    time?: T;
                    desc?: T;
                    image?: T;
                    link?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        regionalDrivesText?:
          | T
          | {
              kicker?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        galleryStrip?:
          | T
          | {
              kicker?: T;
              title?: T;
              accent?: T;
              speed?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        reviews?:
          | T
          | {
              kicker?: T;
              title?: T;
              accent?: T;
              intro?: T;
              limit?: T;
              selectedReviews?: T;
              id?: T;
              blockName?: T;
            };
        faqShort?:
          | T
          | {
              kicker?: T;
              title?: T;
              accent?: T;
              subtext?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        faqSection?:
          | T
          | {
              leftKicker?: T;
              leftTitle?: T;
              leftAccent?: T;
              leftLead?: T;
              quickFacts?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    value?: T;
                    subtitle?: T;
                    id?: T;
                  };
              rightKicker?: T;
              rightTitle?: T;
              rightAccent?: T;
              rightLead?: T;
              enableSearch?: T;
              enableCategoryTabs?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        contactSection?:
          | T
          | {
              kicker?: T;
              title?: T;
              accent?: T;
              lead?: T;
              email?: T;
              phone?: T;
              whatsappNumber?: T;
              whatsappLabel?: T;
              locationAddress?: T;
              googleMapsUrl?: T;
              showFaqCard?: T;
              faqCardTitle?: T;
              faqCardText?: T;
              faqCardLinkLabel?: T;
              faqCardLinkUrl?: T;
              enableMap?: T;
              mapLatitude?: T;
              mapLongitude?: T;
              mapZoom?: T;
              id?: T;
              blockName?: T;
            };
        bookingSection?:
          | T
          | {
              stepsTitle?: T;
              steps?:
                | T
                | {
                    num?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              privilegesTitle?: T;
              privileges?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              hostImage?: T;
              hostName?: T;
              hostSubtitle?: T;
              badgeText?: T;
              whatsappLabel?: T;
              whatsappNumber?: T;
              phone?: T;
              email?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discover-posts_select".
 */
export interface DiscoverPostsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  categoryRef?: T;
  tag?: T;
  badge?: T;
  externalLink?: T;
  mapsUrl?: T;
  desc?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discover-categories_select".
 */
export interface DiscoverCategoriesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drives-distances_select".
 */
export interface DrivesDistancesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  category?: T;
  distance?: T;
  driveTime?: T;
  mapsUrl?: T;
  desc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  category?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories_select".
 */
export interface GalleryCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  stars?: T;
  text?: T;
  source?: T;
  sourceUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categories_select".
 */
export interface FaqCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-inquiries_select".
 */
export interface BookingInquiriesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  country?: T;
  checkIn?: T;
  checkOut?: T;
  adults?: T;
  kids?: T;
  pets?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  consent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  topBar?: {
    phone?: string | null;
    email?: string | null;
    enableLanguages?: boolean | null;
  };
  navItems?:
    | {
        label: string;
        link: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  editorial?: {
    subheading?: string | null;
    heading?: string | null;
    shortBio?: string | null;
  };
  brandTagline?: string | null;
  directBooking?: {
    title?: string | null;
    perk1?: string | null;
    perk2?: string | null;
    perk3?: string | null;
    perk4?: string | null;
    ctaLabel?: string | null;
    ctaLink?: string | null;
  };
  exploreTitle?: string | null;
  navLinks?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  contactSection?: {
    title?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    region?: string | null;
  };
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'whatsapp' | 'tiktok' | 'youtube' | 'airbnb' | 'booking' | 'other';
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * External iCal URL feed used to sync villa availability (e.g. MyLuxoria, Airbnb, Booking.com).
   */
  calendarIcalUrl?: string | null;
  /**
   * When checked, the server always bypasses cache and fetches real-time calendar availability directly from the iCal URL on every visitor page load.
   */
  calendarNoStore?: boolean | null;
  /**
   * How many minutes availability data is cached in memory (default: 15 minutes). Ignored when Real-Time Sync (no-store) is enabled.
   */
  calendarCacheMinutes?: number | null;
  /**
   * Minimum number of consecutive nights required for a direct reservation (e.g. 3 or 7 nights).
   */
  minNights?: number | null;
  /**
   * Timestamp when the calendar feed was last retrieved and synced from the iCal link.
   */
  calendarLastSyncedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  topBar?:
    | T
    | {
        phone?: T;
        email?: T;
        enableLanguages?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        newTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  editorial?:
    | T
    | {
        subheading?: T;
        heading?: T;
        shortBio?: T;
      };
  brandTagline?: T;
  directBooking?:
    | T
    | {
        title?: T;
        perk1?: T;
        perk2?: T;
        perk3?: T;
        perk4?: T;
        ctaLabel?: T;
        ctaLink?: T;
      };
  exploreTitle?: T;
  navLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  contactSection?:
    | T
    | {
        title?: T;
        email?: T;
        phone?: T;
        address?: T;
        region?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  calendarIcalUrl?: T;
  calendarNoStore?: T;
  calendarCacheMinutes?: T;
  minNights?: T;
  calendarLastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}